name: 'Semantic release check'
description: 'This action checks the semantic release type of a pull request.'
inputs:
  repo-token:
    description: 'github token for creating commit'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
